---
settings:
  name: Cloud Volumes Service
  platform: ''
  rss_page: reference_whats_new_cloud_volumes_aws.html
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: it-it,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,es-es,fr-fr
sidebar:
  entries:
  - title: Cloud Volumes Service per documenti AWS
    url: "/aws/index.html"
  - title: Note di rilascio
    entries:
    - title: Novità
      url: "/aws/reference_whats_new_cloud_volumes_aws.html"
    - title: Problemi noti
      url: "/aws/reference_known_issues.html"
  - title: Per iniziare
    entries:
    - title: Prerequisiti
      url: "/aws/concept_overview.html"
    - title: Istruzioni di avvio rapido
      url: "/aws/task_quick_start.html"
    - title: Attivazione dei diritti di supporto e accesso al supporto
      url: "/aws/task_activating_support_entitlement.html"
    - title: Selezione della regione
      url: "/aws/task_selecting_region.html"
  - title: Gestione dei volumi cloud
    entries:
    - title: Creazione di un volume cloud
      url: "/aws/task_creating_cloud_volumes_for_aws.html"
    - title: Montaggio di un volume cloud
      url: "/aws/task_mounting_cloud_volumes_for_aws.html"
    - title: Modifica di un volume cloud
      url: "/aws/task_modifying_cloud_volumes_for_aws.html"
    - title: Eliminazione di un volume cloud
      url: "/aws/task_deleting_cloud_volumes_for_aws.html"
  - title: Gestione delle snapshot dei volumi cloud
    entries:
    - title: Creazione di uno snapshot on-demand per un volume cloud
      url: "/aws/task_creating_on_demand_snapshots.html"
    - title: Creazione o modifica di un criterio di snapshot
      url: "/aws/task_creating_modifying_snapshot_policies.html"
    - title: Disattivazione di un criterio di snapshot
      url: "/aws/task_disabling_snapshot_policy.html"
    - title: Ripristino di un volume da uno snapshot
      url: "/aws/task_reverting_volume_to_snapshot.html"
    - title: Eliminazione di uno snapshot
      url: "/aws/task_deleting_snapshots.html"
    - title: Ripristino di uno snapshot in un nuovo volume
      url: "/aws/task_restoring_snapshots_to_new_volumes.html"
  - title: Gestione delle regole dei criteri di esportazione
    entries:
    - title: Modifica di una regola dei criteri di esportazione
      url: "/aws/task_modifying_export_policy_rules.html"
    - title: Creazione di regole aggiuntive per i criteri di esportazione
      url: "/aws/task_creating_additional_export_policy_rules.html"
    - title: Eliminazione delle regole dei criteri di esportazione
      url: "/aws/task_deleting_export_policy_rules.html"
  - title: Gestione di Cloud Sync per i volumi cloud
    entries:
    - title: Creazione di un data broker Cloud Sync
      url: "/aws/task_creating_cloud_sync_data_broker.html"
    - title: Creazione di una relazione Cloud Sync
      url: "/aws/task_creating_cloud_sync_relationship.html"
    - title: Modifica della pianificazione Cloud Sync
      url: "/aws/task_modifying_cloud_sync_schedule.html"
    - title: Eliminazione di una relazione Cloud Sync
      url: "/aws/task_deleting_cloud_sync_relationship.html"
    - title: Eliminazione di un broker di dati Cloud Sync
      url: "/aws/task_deleting_cloud_sync_data_broker.html"
  - title: API Cloud Volumes
    url: "/aws/reference_cloud_volume_apis.html"
  - title: Riferimento
    entries:
    - title: Impostazioni del gruppo di protezione AWS per i server Windows ad
      url: "/aws/reference_security_groups_windows_ad_servers.html"
    - title: Selezione del livello di servizio appropriato e della capacità allocata
      url: "/aws/reference_selecting_service_level_and_quota.html"
  - title: Note legali
    url: "/aws/reference_notices.html"
