---
sidebar: sidebar 
permalink: aws/reference_whats_new_cloud_volumes_aws.html 
keywords: 'Cloud Volumes Service for AWS, what"s new, features, enhancements' 
summary: NetApp aggiorna periodicamente Cloud Volumes Service per AWS per offrire nuove funzionalità e miglioramenti. 
---
= Novità di Cloud Volumes Service per AWS
:toc: macro
:hardbreaks:
:allow-uri-read: 
:toc: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
NetApp aggiorna periodicamente Cloud Volumes Service per AWS per offrire nuove funzionalità e miglioramenti.



== Febbraio 2021

* Una nuova API Cloud Volumes (`PerformanceMetrics`) È ora disponibile per recuperare le statistiche sulle performance, tra cui IOPS, larghezza di banda e latenza. Per ulteriori informazioni, vedere link:reference_cloud_volume_apis.html["API Cloud Volumes"^].




== Luglio 2020

* Cloud Volumes Service supporta ora intervalli di rete privata RFC 1918 più ampi, compresi tra /16 e /28. In precedenza erano supportati solo /28 intervalli.
* La funzione "Sync" si integra direttamente con l'interfaccia utente di Cloud Sync per offrire maggiori funzionalità.
* I volumi possono essere convertiti in e da NSFv3, NFSv4.1 e NFSv3 e NFSv4.1 tramite chiamate API.
* Gli esempi API e gli script Python di esempio sono stati aggiornati all'API v2. link:reference_cloud_volume_apis.html["Vedere API Cloud Volumes"].
* Gli ACL sono ora abilitati per i volumi NFSv4.1.
* Cloud Volumes Service è ora certificato con SOC 2 tipo 1.
* Cloud Volumes Service è ora disponibile a Singapore (ap-sud-est-1).




== Marzo 2020

* Cloud Volumes Service supporta ora una dimensione i/o massima di 1 MIB per i supporti NFSv3 e NFSv4.1. In precedenza, la dimensione massima di i/o era di 64 KiB. L'aumento delle dimensioni di i/o può migliorare le performance per alcuni carichi di lavoro. Per aumentare le dimensioni i/o, utilizzare le opzioni di montaggio "rsize" e/o "wsize", ad esempio:
`mount -o nfsvers=4.1,rsize=1048576,wsize=1048576 172.25.0.4:/vol1 /mnt/cv`




== Febbraio 2020

* Cloud Volumes Service è ora disponibile come abbonamento misurato (pay-as-you-go) nel marketplace AWS. Per ulteriori informazioni, consulta l'elenco di Marketplace all'indirizzo: https://aws.amazon.com/marketplace/pp/B0848MXK74[]Si noti che i piani di abbonamento mensili e annuali originali sono ancora disponibili.




== Gennaio 2020

* Cloud Volumes Service ora supporta SMB multicanale che utilizza più connessioni di rete contemporaneamente per offrire performance migliori. Il multicanale è attivato per impostazione predefinita sui client Windows, ma richiede che l'istanza EC2 utilizzi un adattatore di rete che supporti RSS (Receive Side Scaling).
* Il ripristino di un volume da uno snapshot è ora disponibile dall'interfaccia utente di Cloud Volumes Service. In questo modo è possibile ripristinare i volumi a un'istantanea point-in-time senza dover eseguire il remount dei client. Vedere link:task_reverting_volume_to_snapshot.html["Ripristino di un volume da uno snapshot"] per ulteriori informazioni.

